#!/bin/sh
# Script to start/stop node-monitor
#
MONITOR_INSTALL_DIR=/root/src/node-monitor
export STATSD_HOST=216.191.247.86
case "$1" in
     start)
		echo "Starting service"
		SAVE=`pwd`
		cd $MONITOR_INSTALL_DIR
		node monitor.js >& /tmp/node-monitor.log &
		cd "${SAVE}"
		;;
	  stop)
		echo "Stopping service"
		PID=`ps -ef | grep "node monitor.js" | grep -v grep | awk '{ print $2 }'`
		if [ "$PID" != "" ] ; then
			echo "$PID" | xargs kill
		fi
		;;
	  restart)
		echo "Stopping service"
		PID=`ps -ef | grep "node monitor.js" | grep -v grep | awk '{ print $2 }'`
		if [ "$PID" != "" ] ; then
			echo "$PID" | xargs kill
		fi
		echo "Starting service"
		SAVE=`pwd`
		cd $MONITOR_INSTALL_DIR
		node monitor.js >& /tmp/node-monitor.log &
		cd "${SAVE}"
		;;
	  status)
		ps -ef | grep "node monitor.js" | grep -v grep
		;;
	  *)
		echo "Usage: $0 { start|stop|status|restart }"
		exit 1
esac
exit $?
